#!/bin/sh
set -e

VENV_DIR="/opt/gecko-controller/venv"

case "$1" in
    remove|purge)
        # Stop and disable the service
        systemctl stop gecko-controller || true
        systemctl disable gecko-controller || true

        # Remove the virtual environment
        rm -rf "$VENV_DIR"
        ;;
esac

# Automatically added by dh_installinit/13.11.4
if [ "$1" = "remove" ] && [ -x "/etc/init.d/gecko-controller" ] ; then
	chmod -x "/etc/init.d/gecko-controller" >/dev/null || true
fi
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = "purge" ] ; then
	update-rc.d gecko-controller remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_systemd_start/13.11.4
if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_systemd_enable/13.11.4
if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'gecko-controller.service' 'gecko-web.service' >/dev/null || true
	fi
fi
# End automatically added section

