name: Build Check

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Make scripts executable
        run: |
          chmod +x tools/verify-versions.sh

      - name: Verify versions
        run: tools/verify-versions.sh

      - name: Build package
        run: make all

      - name: Move build artifacts to workspace
        run: |
          mkdir -p artifacts
          cp ../*.deb artifacts/
          cp ../*.buildinfo artifacts/
          cp ../*.changes artifacts/

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: debian-packages
          path: artifacts/
          if-no-files-found: error
